exp_name: "'@{network.name}'_'@{trainer.name}'_'@{dataset.name}'_e'@{optimizer.num_epochs}'_lr'@{optimizer.lr}'_wd'@{optimizer.weight_decay}'_'@{mark}'"
output_dir: ./results/
save_output: True
force_merge: True # disabled if 'save_output' is False
num_classes: '@{dataset.num_classes}'
mark: DIS_ImageNet100_generative # to mark the version of experiment

num_gpus: 1
num_workers: 8
num_machines: 1
machine_rank: 0
epoch: 1

seed: 3407

pipeline:
  name: SP_base

evaluator:
  name: SP
  mode: weight
  recall: 0.95
  score_set: all
  th_p: null
  th_all: null

optimizer:
  num_epochs: 10
  logbatch: 100
  learning_rate: 0.0002
  lr: 0.0002
  momentum: 0.9
  weight_decay: 5.0e-06

recorder:
  name: SP
  save_all_models: False

preprocessor:
  name: ImageNet

postprocessor:
  name: SP
  mode: loss
  postprocessor_args:
    temperature: 1

parameters:
  var_loc: 3
  var_cov: 0.005
  eps_low: 1
  eps_high: 20

network:
  name: X_sep
  num_classes: '@{dataset.num_classes}'
  pretrained: false          # set 'True' to load pretrained model
  checkpoint: ./networks/xception-b5690688.pth
  num_gpus: '@{num_gpus}'

