dataset:
  name: DIS_ImageNet100
  split_names: [train, val, test]
  num_classes: 2
  pre_size: 224
  image_size: 256
  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'
  dataset_name: 'ImageNet100'
  mode: DIS
  eps: 4
  train:
    dataset_class: ImglistDataset_SP
    data_dir: 
    imglist_pth: ./data/SP_general_new/imagenet100_train.labels.txt
    batch_size: 32
    shuffle: True
    interpolation: bilinear
  test:
    dataset_class: ImglistDataset
    batch_size: 32
    shuffle: False
    interpolation: bilinear

    set_names: [Real, Gradient-advs]
    Real:
      data_dir: 
      imglist_pth: ./data/SP_general_new/imagenet100_test.labels.txt
    Gradient-advs:
      subsets: ['FGSM', 'PGD']
      FGSM:
        data_dir: 
        imglist_pth: ./data/SP_general_new/imagenet100-FGSM-eps4_test.labels.txt
      PGD:
        data_dir: 
        imglist_pth: ./data/SP_general_new/imagenet100-PGD-eps4_test.labels.txt
