dataset:
  name: DIS_GAN_Diffusion
  split_names: [train, val, test]
  num_classes: 2
  pre_size: 256
  image_size: 256
  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'
  dataset_name: 'ImageNet100'
  mode: GC_n
  eps: 4
  train:
    dataset_class: ImglistDataset_SP
    data_dir: 
    imglist_pth: ./data/SP_general_new/imagenet100_train.labels.txt
    batch_size: 32
    shuffle: True
    interpolation: bilinear
  val:
    dataset_class: ImglistDataset
    batch_size: 32
    shuffle: False
    interpolation: bilinear

    set_names: [Real, Generative-advs]
    Real:
      data_dir: 
      imglist_pth: ./data/SP_general_new/imagenet100-real-img-eps4_val.labels.txt
    Generative-advs:
      subsets: [CDA, diff-pgd]
      CDA:
        data_dir: 
        imglist_pth: ./data/SP_general_new/imagenet100-FGSM-eps4_val.labels.txt
      diff-pgd:
        data_dir: 
        imglist_pth: ./data/SP_general_new/imagenet100-RFGSM-eps4_val.labels.txt

  test:
    dataset_class: ImglistDataset
    batch_size: 32
    shuffle: False
    interpolation: bilinear

    set_names: [Real, Generative-advs]
    Real:
      data_dir: 
      imglist_pth: ./data/SP_general_new/imagenet100-real-img-eps4_test.labels.txt
    Generative-advs:
      subsets: [CDA, diff-pgd]
      CDA:
        data_dir: 
        imglist_pth: ./data/SP_general_new/imagenet100-CDA-eps4_test.labels.txt
      diff-pgd:
        data_dir: 
        imglist_pth: ./data/SP_general_new/imagenet100-diff-pgd-eps4_test.labels.txt
